const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with:", deployer.address);

  // 1. Deploy TokenFaucet
  const Faucet = await ethers.getContractFactory("TokenFaucet");
  const faucet = await Faucet.deploy();
  await faucet.waitForDeployment();
  const faucetAddress = await faucet.getAddress();
  console.log("TokenFaucet deployed to:", faucetAddress);

  // 2. Deploy ProofOfReading
  const Digest = await ethers.getContractFactory("ProofOfReading");
  const digest = await Digest.deploy(faucetAddress);
  await digest.waitForDeployment();
  const digestAddress = await digest.getAddress();
  console.log("ProofOfReading deployed to:", digestAddress);

  // 3. Write addresses to src/addresses.js
  const out = `// Auto-generated by deploy.js — do not edit manually
export const FAUCET_ADDRESS = "${faucetAddress}";
export const DIGEST_ADDRESS = "${digestAddress}";
`;
  const outPath = path.join(__dirname, "..", "src", "addresses.js");
  fs.writeFileSync(outPath, out);
  console.log("Addresses written to src/addresses.js");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});