// Auto-generated by deploy.js — do not edit manually
export const FAUCET_ADDRESS = "0xDcdc55d38529231bfca066570290a4834429ffC3";
export const DIGEST_ADDRESS = "0x28780957E1A38108006d7161784bBB8e790FEb10";
